import { Ticket } from "./ticket";

export interface TicketComment {
    // commentId: number;
    // The ID of the comment (auto-generated by the backend)

    ticketId: Number;
    // ticket: Ticket;
    // The ticket associated with this comment

    commentText: string;
    // The text of the comment

    commentDate: Date;
    // The date and time when the comment was posted

    commentBy: String
    // commentBy: 'Customer' | 'Engineer' | 'Manager';
    // Who posted the comment ('Customer', 'Engineer', or 'Manager')
}